#! /bin/zsh
bspc rule -r "*"
sxhkd &
autostart &
bspc monitor -d  1 2 3 4 5 
 
bspc config border_width         3
bspc config window_gap           10
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config history_aware_focus  true

bspc config normal_border_color		"#0E152F"
bspc config focused_border_color	"#fffbf6"

bspc rule -a Gcolor3 state=floating
bspc rule -a Galculator state=floating
bspc rule -a mpv state=fullscreen
bspc rule -a Steam state=floating
bspc rule -a Yad --name yad-calendar state=floating 
bspc rule -a UXTerm state=floating 
bspc rule -a csgo_linux64 desktop=^2
bspc rule -a hl2_linux desktop=^2
bspc rule -a upc.exe state=tiling
